version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - app_bundle:/usr/local/bundle
      - .:/app_root

volumes:
  app_bundle:
    external: false
